# action.yml
name: 'Trusty'
on: push
jobs: 
  test-ctf-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the container
        run: docker build . -t ctf_image
        
