# action.yml
name: 'Trusty'
on: push
jobs: 
  test-ctf-container:
    runs-on: ubuntu-latest
    steps:
      - name: Build the container
        run: ls trusty/ ; docker build trusty/ --file Dockerfile -t ctf_image
